#!/usr/bin/env python3
"""Writes ios/PickThePlay/Models/TeamPresets.swift from teams.py (the website's Create Game presets).

    python3 ios/scripts/make_team_presets.py          # rewrite the Swift file
    python3 ios/scripts/make_team_presets.py --check  # exit 1 if it is out of date (tests/test_ios_team_presets.py)
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "ios" / "PickThePlay" / "Models" / "TeamPresets.swift"
sys.path.insert(0, str(ROOT))


def render() -> str:
    from teams import TEAM_PRESETS

    rows = ",\n".join(
        '        TeamPreset(name: "{name}", label: "{label}", primary: "{primary}", secondary: "{secondary}")'.format(**t)
        for t in TEAM_PRESETS
    )
    return f"""// Generated by ios/scripts/make_team_presets.py from teams.py. Do not edit by hand.
// (tests/test_ios_team_presets.py fails when this file is out of date.)

import Foundation

/// A city with its real team colours, for "Choose the teams yourself" when a game can't come from the live schedule.
struct TeamPreset: Equatable, Identifiable {{
    var name: String
    /// What the picker shows; the two cities with two clubs say which colours.
    var label: String
    var primary: String
    var secondary: String

    var id: String {{ label }}
    var choice: TeamChoice {{ TeamChoice(name: name, primary: primary, secondary: secondary) }}

    static let all: [TeamPreset] = [
{rows},
    ]
}}
"""


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        sys.exit(0 if OUT.exists() and OUT.read_text() == text else 1)
    OUT.write_text(text)
    print("wrote", OUT.relative_to(ROOT))
