// Generated by ios/scripts/make_team_presets.py from teams.py. Do not edit by hand.
// (tests/test_ios_team_presets.py fails when this file is out of date.)

import Foundation

/// A city with its real team colours, for "Choose the teams yourself" when a game can't come from the live schedule.
struct TeamPreset: Equatable, Identifiable {
    var name: String
    /// What the picker shows; the two cities with two clubs say which colours.
    var label: String
    var primary: String
    var secondary: String

    var id: String { label }
    var choice: TeamChoice { TeamChoice(name: name, primary: primary, secondary: secondary) }

    static let all: [TeamPreset] = [
        TeamPreset(name: "Arizona", label: "Arizona", primary: "#97233F", secondary: "#FFB612"),
        TeamPreset(name: "Atlanta", label: "Atlanta", primary: "#A71930", secondary: "#A5ACAF"),
        TeamPreset(name: "Baltimore", label: "Baltimore", primary: "#241773", secondary: "#9E7C0C"),
        TeamPreset(name: "Buffalo", label: "Buffalo", primary: "#00338D", secondary: "#C60C30"),
        TeamPreset(name: "Carolina", label: "Carolina", primary: "#0085CA", secondary: "#101820"),
        TeamPreset(name: "Chicago", label: "Chicago", primary: "#0B162A", secondary: "#C83803"),
        TeamPreset(name: "Cincinnati", label: "Cincinnati", primary: "#FB4F14", secondary: "#000000"),
        TeamPreset(name: "Cleveland", label: "Cleveland", primary: "#311D00", secondary: "#FF3C00"),
        TeamPreset(name: "Dallas", label: "Dallas", primary: "#003594", secondary: "#869397"),
        TeamPreset(name: "Denver", label: "Denver", primary: "#FB4F14", secondary: "#002244"),
        TeamPreset(name: "Detroit", label: "Detroit", primary: "#0076B6", secondary: "#B0B7BC"),
        TeamPreset(name: "Green Bay", label: "Green Bay", primary: "#203731", secondary: "#FFB612"),
        TeamPreset(name: "Houston", label: "Houston", primary: "#03202F", secondary: "#A71930"),
        TeamPreset(name: "Indianapolis", label: "Indianapolis", primary: "#002C5F", secondary: "#A2AAAD"),
        TeamPreset(name: "Jacksonville", label: "Jacksonville", primary: "#006778", secondary: "#D7A22A"),
        TeamPreset(name: "Kansas City", label: "Kansas City", primary: "#E31837", secondary: "#FFB81C"),
        TeamPreset(name: "Las Vegas", label: "Las Vegas", primary: "#A5ACAF", secondary: "#000000"),
        TeamPreset(name: "Los Angeles", label: "Los Angeles (royal blue & gold)", primary: "#003594", secondary: "#FFA300"),
        TeamPreset(name: "Los Angeles", label: "Los Angeles (powder blue & gold)", primary: "#0080C6", secondary: "#FFC20E"),
        TeamPreset(name: "Miami", label: "Miami", primary: "#008E97", secondary: "#FC4C02"),
        TeamPreset(name: "Minnesota", label: "Minnesota", primary: "#4F2683", secondary: "#FFC62F"),
        TeamPreset(name: "New England", label: "New England", primary: "#002244", secondary: "#C60C30"),
        TeamPreset(name: "New Orleans", label: "New Orleans", primary: "#D3BC8D", secondary: "#101820"),
        TeamPreset(name: "New York", label: "New York (blue & red)", primary: "#0B2265", secondary: "#A71930"),
        TeamPreset(name: "New York", label: "New York (green & white)", primary: "#125740", secondary: "#FFFFFF"),
        TeamPreset(name: "Philadelphia", label: "Philadelphia", primary: "#004C54", secondary: "#A5ACAF"),
        TeamPreset(name: "Pittsburgh", label: "Pittsburgh", primary: "#FFB612", secondary: "#101820"),
        TeamPreset(name: "San Francisco", label: "San Francisco", primary: "#AA0000", secondary: "#B3995D"),
        TeamPreset(name: "Seattle", label: "Seattle", primary: "#002244", secondary: "#69BE28"),
        TeamPreset(name: "Tampa Bay", label: "Tampa Bay", primary: "#D50A0A", secondary: "#FF7900"),
        TeamPreset(name: "Tennessee", label: "Tennessee", primary: "#0C2340", secondary: "#4B92DB"),
        TeamPreset(name: "Washington", label: "Washington", primary: "#5A1414", secondary: "#FFB612"),
    ]
}
